# define the `Secret` to define the necessary environment variables for the mongo server and mongo-express. (admin|password123)
apiVersion: v1
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQxMjM=
kind: Secret
metadata:
  name: mongo-secret